python main_train.py \
--image_dir data/iu_xray/images/ \
--ann_path data/iu_xray/annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 16 \
--epochs 100 \
--step_size 50 \
--gamma 0.1 \
--seed 9223 \
--visual_extractor vit_b_16 \
--weights IMAGENET1K_SWAG_E2E_V1 \
--d_vf 768 \
--monitor_metric CIDEr \
--n_gpu 4 \
--frozen \
--cls \
--early_stop 100 \
--record_dir recordsnew/recordsfrozentranswithcls \
--save_dir recordsnew/resultsfrozentranswithcls